### PR TITLE
ADD: twitterEngagement

### PR DESCRIPTION
**Pull request by jagreene**

### CODE REVIEW

**Comment by anneCarlson** [comment]
This doesn't pass! Where do you hit up the `http://apiv2.indico.io/engagement` endpoint?

**Comment by sihrc** [comment]
No worries @anneCarlson. Looks like it was because the boxes weren't up yet :+1:

**Comment by sihrc** [comment]
Simple add, LGTM :+1:

**Comment by madisonmay** [comment]
Wow updating node is so pleasant.  Looks good to me, let's merge this thing.

**Pull request merged**
