### PR TITLE
FIX: Support for keyword args and config.api_key --> config.apiKey

### PR DESCRIPTION
**Pull request by madisonmay**

### CODE REVIEW

**Comment by sihrc** [comment]
What was the reason for this change out of curiosity? For consistency?

**Comment by madisonmay** [comment]
Consistency with what is expected for node (for the api_key --> apiKey bit).

**Comment by madisonmay** [comment]
For adding support for keyword args, it's something we've already done in python / ruby and have implemented on the server, so it makes sense for us to expose it via the client.

**Comment by sihrc** [comment]
Oh okay, cool. Well, it looks pretty good to me

**Pull request merged**
